### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Decending** [markhakansson/rtic_f4xx_nucleo#1]
src:
D) You haven’t answered this question, simply run the program and paste the answers in. Most likely a small oversight.

Examples:
rtt_timing:
Saknas svar för B1
Saknas svar för C1
E) The contents of R1 is the cycle count and you are correct in finding to function call, as get cycle count is optimized out of the program in release.

timing_tasks:
Good job! Translating the hexadecimals to decimals might be useful just for clarity, but it’s a minor thing.

timing_resources:
Extend your answer regarding the priority, why does the priority make it safe? (line 147)
Correct answer at line 179, you might just have written the wrong answer at line 175 (should be 52)
The final calculation is missing the foot print program, the resource is loaded twice during runtime and considering both exti0 and exti1 will run we will have to multiply the job latency with two as well.

**Comment by markhakansson** [comment]
Ok thanks forgot a lot of stuff! I fixed it now :)
